export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";


export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";



// export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
// export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
// export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";


// export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
// export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
// export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";


// export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
// export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";


export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const REGISTRY_CONFIRM = "REGISTRY_CONFIRM";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";